# define Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: growi-tools
---
# Storege
## for growi-app
apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-growi-app
  namespace: growi-tools
spec: 
  capacity: 
    storage: 16Gi 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-growi-app
  gcePersistentDisk: 
    pdName: growi-disk-01
    fsType: ext4 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-growi-app
  namespace: growi-tools
spec: 
  accessModes: 
    - ReadWriteOnce
  storageClassName: sc-growi-app
  resources: 
    requests: 
      storage: 16Gi
---
## for growi-mongodb
apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-growi-mongodb
  namespace: growi-tools
spec: 
  capacity: 
    storage: 16Gi 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-growi-mongodb
  gcePersistentDisk: 
    pdName: growi-disk-02
    fsType: ext4 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-growi-mongodb
  namespace: growi-tools
spec: 
  accessModes: 
    - ReadWriteOnce
  storageClassName: sc-growi-mongodb
  resources: 
    requests: 
      storage: 16Gi
---
# Database(mongo)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: growi-mongo
  namespace: growi-tools
  labels:
    app: growi-mongo
spec:
  serviceName: "growi-mongo"
  selector:
    matchLabels:
      app: growi-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: growi-mongo
      name: growi-mongo
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: growi-mongo
        image: mongo:3.6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: growi-mongodb-data
          mountPath: /data
      volumes: 
      - name: growi-mongodb-data
        persistentVolumeClaim: 
          claimName: pvc-growi-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: sv-growi-mongo
  namespace: growi-tools
  labels:
    app: growi-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: growi-mongo
---
# Elasticsearch
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: growi-elasticsearch
  namespace: growi-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: growi-elasticsearch
    spec:
      containers:
      - name: growi-elasticsearch
        image: elasticsearch:5.3-alpine
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        command: ["sh", "-c", "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji;./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;/docker-entrypoint.sh elasticsearch"]
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: growi-elasticsearch
  name: sv-growi-elasticsearch
  namespace: growi-tools
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: growi-elasticsearch
---
# Growi Application
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: growi-app
  namespace: growi-tools
  labels:
    app: growi-app
spec:
  selector:
    matchLabels:
      app: growi-app
  replicas: 1 # 共有ディスクでpodの2つ目を建てようとするとmountでコケる致命的なエラーがあるため、実質1が上限である
  template:
    metadata:
      labels:
        app: growi-app
      name: growi-app
    spec:
      containers:
      - name: growi-app
        image: weseek/growi:3
        env:
        - name: MONGO_URI
          value: "mongodb://sv-growi-mongo:27017/growi"
        - name: ELASTICSEARCH_URI
          value: "http://sv-growi-elasticsearch:9200/growi"
        - name: PASSWORD_SEED
          value: "changeme"
        - name: FILE_UPLOAD
          value: "local"
        - name: FORCE_WIKI_MODE
          value: "private"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /_api/v3/healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: growi-data
          mountPath: /data
      volumes: 
      - name: growi-data
        persistentVolumeClaim: 
          claimName: pvc-growi-app
---
apiVersion: v1
kind: Service
metadata:
  name: sv-growi-app
  namespace: growi-tools
  labels:
    app: growi-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: growi-app
---
# Ingress and Certificate and IP settings
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: cert-growi-app
  namespace: growi-tools
spec:
  domains:
    - dev.wiki.hotstaff-dev.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-growi
  namespace: growi-tools
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "ip-growi"
    networking.gke.io/managed-certificates: "cert-growi-app"
spec:
  rules:
  - host: dev.wiki.hotstaff-dev.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: sv-growi-app
          servicePort: 80
