apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: growis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.4
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: growis
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
